### ISSUE TITLE
Will the lib parse terraform plan file?

### ISSUE THREAD

**Issue by renou** [virtru/tfstate#4]
Hi! Just curious, will the lib parse terraform plan file?

Thanks!

**Comment by conorgil** [comment]
@renou I assume that you are talking about using [terraform plan -out](https://www.terraform.io/docs/commands/plan.html#out-path0, right? `tfstate` is intended to read the raw JSON state file and the `plan -out` file appears not to be JSON, so I expect it won't work.

I will say that I have not used the `plan -out` feature of Terraform and I am not familiar with the contents of the file, so it is possible that something could work. I would recommend testing it out and reporting back whether it works or not for you.

**Comment by renou** [comment]
Thanks for answering! 👍
